export default {
    "app.title": "Moje počasí",
    welcome: "Vítejte",
    cs: "čeština",
    en: "angličtina",
    "login.sign_in": "Přihlásit se",
    "login.sign_up": "Zaregistrovat se",
    "login.name": "Jméno",
    "login.password": "Heslo",
    "login.password_confirm": "Potvrzení hesla",
    "login.email": "E-mail",
    "login.remember_me": "Pamatuj si mě",
    "login.forgot_password": "Zapomněli jste heslo?",
    "login.no_account": "Nemáte účet? Zaregistrujte se",
    "login.required_field": "Toto pole je povinné",
    "login.confirmation_failed": "Hesla musí být stejná",
    "login.email_wrong_format": "Neplatný formát e-mailu",
    "profile.title": "Profil",
    "login.sign_out": "Odhlásit se",
    "error.not_found": "Nenalezeno",
    "error.not_exist_msg": "Jejda, zdá se, že tato stránka neexistuje",
    "weather.title": "Počasí",
    "saved-locations.title": "Uložená místa",
    "home.positionDenied": "Pozice odepřena",
    "common.loading": "Načítání...",
    "weather-details.today": "Dnešní počasí",
    "weather-details.forecast": "Předpověď pro dalších 7 dní",
    "common.latitude": "zeměpisná šířka",
    "common.longitude": "zeměpisná délka",
    "place-card.check_weather": "Zkontrolovat počasí",
    "common.copyright": "Autorská práva © ",
};
