export default {
    "app.title": "My Weath",
    welcome: "Vítej",
    cs: "Čeština",
    en: "English",

    "login.sign_in": "Přihlášení",
    "login.sign_up": "Registrace",
    "login.name": "Název",
    "login.password_confirm": "Heslo znovu",
    "login.password": "Heslo",
    "login.email": "Email",
    "login.remember_me": "Zapamatovat údaje",
    "login.forgot_password": "Zapomněli jste heslo?",
    "login.no_account": "Nemáš účet? Zaregistruj se",
    "login.required_field": "Toto pole je povinné",
    "login.confirmation_failed": "Hesla musí být stejná",
    "login.email_wrong_format": "Není validní formát pro email",
    "profile.title": "Profile",
    "login.sign_out": "Sign out",
    "error.not_found": "Nenalezeno",
    "error.not_exist_msg": "Oops, vypadá to, že tato stránka neexistuje",
    "weather.title": "Weather",
    "home.positionDenied": "Position denied",
    "saved-locations.title": "Saved locations",
    "forecast.next_7_days": "Předpověď pro dalších 7 dní",
    "today": "Dnes",
    "signup.success": "Registrace proběhla v pořádku!",
    loading: "Načítání...",
};
