export default {
    "app.title": "My Weath",
    welcome: "Welcome",
    cs: "Czech",
    en: "English",

    "login.sign_in": "Sign in",
    "login.sign_up": "Sign up",
    "login.name": "Name",
    "login.password": "Password",
    "login.password_confirm": "Password confirmation",
    "login.email": "Email",
    "login.remember_me": "Remember me",
    "login.forgot_password": "Forgot password?",
    "login.no_account": "Don't have an account? Sign Up",
    "login.required_field": "This field is required",
    "login.confirmation_failed": "Passwords must be the same",
    "login.email_wrong_format": "Not valid email format",
    "profile.title": "Profile",
    "login.sign_out": "Sign out",
    "error.not_found": "Not found",
    "error.not_exist_msg": "Oops, looks like this page does not exist",
    "weather.title": "Weather",
    "saved-locations.title": "Saved locations",
    "home.positionDenied": "Position denied",
    "common.loading": "Loading...",
    "weather-details.today": "Today's weather",
    "weather-details.forecast": "Forecast for the next 7 days",
    "common.latitude": "Latitude",
    "common.longitude": "Longitude",
    "place-card.check_weather": "Check weather",
    "common.copyright": "Copyright © ",
    "signup.success":"Registration successful!",
    today: "Today",
};
